source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'AsyncKit_Tests' do
  pod "AsyncKit", :path => "../"

  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-3.0'
end

# cf. http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
