source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'AsyncKit_Tests', :exclusive => true do
  pod "AsyncKit", :path => "../"

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 3.0'
end
